name: Publish project to SakuraMC RepositoryServer

on:
  push:
    branches: [ master ]
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: gradle/actions/wrapper-validation@v3
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: adopt
          java-version: 21
      - name: Publish with Gradle
        run: ./gradlew publishAllPublicationsToSakuraRepositoryRepository
        env:
          MAVEN_NAME: ${{ secrets.MAVEN_NAME }}
          MAVEN_SECRET: ${{ secrets.MAVEN_SECRET }}
